CREATE TABLE `MUNICIPALITIES` (
  `ID`   INT         NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`NAME`)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE `TAXES` (
  `ID`              INT            NOT NULL AUTO_INCREMENT,
  `MUNICIPALITY_ID` INT            NOT NULL,
  `FROM`            VARCHAR(10)    NOT NULL,
  `TO`              VARCHAR(10)    NOT NULL,
  `TAX_TYPE`        VARCHAR(20)    NOT NULL,
  `VALUE`           DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MUNICIPALITY_ID_AND_TAX_TYPE` (`MUNICIPALITY_ID`, `TAX_TYPE`),
  FOREIGN KEY (`MUNICIPALITY_ID`) REFERENCES `MUNICIPALITIES` (`ID`)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;